### ISSUE TITLE
Calicod Experiment room door will not unlock from inside

### ISSUE THREAD

**Issue by Zed287** [zunath/SWLOR_NWN#240] opened 2018-10-20 21:56 UTC
Looks like the key will only work one way, as well I never recieved a key durring this quest on CZ so the door seems like it is bugged in general..

I would suggest not using a key for this door at all for simplicity sake, but if a key is needed to use the door, then have the other side of the door not require a key in case the players bring a party.

**Comment by taelon875** [comment] 2018-10-20 22:02
Keys are a virtual item that you get marked as having in the database, the door never really unlocks.

**Comment by Zed287** [comment] 2018-10-20 22:16
Alright, Ill check back there, Im not sure how i recieved the key considering I never spoke to anyone in CZ with a fresh character

**Comment by zunath** [comment] 2018-10-21 05:18
Keys are tied to your character as part of your "Key Items". You can view these in your rest menu but you can't transfer the key to other players by design. 

I just tried to reproduce this with a character that's missing the key item and I can't. Is it possible the character you used the door on had the Colicoid Experiment quest? You get the key item as part of that quest.

**Comment by zunath** [comment] 2018-10-22 13:27
The NPC you need to talk to is the same guy you hunt Mynocks for. It should be quest number 3 in his line of quests.

I can't reproduce this bug. The door is locked for me as a brand new character. I also tested the "Exit the room" object near the door and it took me out of it. Try it again and if it's still a problem I may need your help testing it on the server

**Closed by zunath** 2018-10-22 13:27 UTC
Labels: bug
