### ISSUE TITLE
Certain placeables are able to be walked through

### ISSUE THREAD

**Issue by Cavcode** [zunath/SWLOR_NWN#31] opened 2018-09-15 18:44 UTC
Seems like some of the placeables, both modern and star wars can be completely walked through. Specifically [SWLOR] Wall, Imp, Med

**Comment by zunath** [comment] 2018-09-18 04:32
Closing this since it's a dupe of #32 . Will track it in that ticket.

**Closed by zunath** 2018-09-18 04:32 UTC
Labels: bug
