### ISSUE TITLE
GAME: [Enhancement] Add a way for early players to get Destroyed fiberplast

### ISSUE THREAD

**Issue by extaz93** [zunath/SWLOR_NWN#337] opened 2018-10-28 23:32 UTC
I can build a Scavenger NPC selling destroyed fiberplast for 30 GP,
So it's not that cheap, but still.

**Comment by zunath** [comment] 2018-10-29 02:49
Dupe of https://github.com/zunath/SWLOR_NWN/issues/303

**Closed by zunath** 2018-10-29 02:49 UTC
